const SCREEN_PATH = {
  LOGIN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER_SCREEN',
  DASHBOARD: 'DASHBOARD_SCREEN',
  PRODUCT: 'PRODUCT_SCREEN',
  TRANSACTION: 'TRANSACTION_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  CHANGE_PROFILE: 'CHANGE_PROFILE_SCREEN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD_SCREEN',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL_SCREEN',
  EDIT_PRODUCT: 'EDIT_PRODUCT_SCREEN',
  ADD_PRODUCT: 'PRODUCT_FORM_SCREEN',
  ARTICLE_DETAIL: 'ARTICLE_DETAIL_SCREEN',
  MAIN_APP: 'MAIN_APP',
};

const TAB_PATH = {
  DASHBOARD: 'Halaman Utama',
  PRODUCT: 'Produk',
  TRANSACTION: 'Transaksi',
  PROFILE: 'Profil',
};

export { SCREEN_PATH, TAB_PATH };
