const SCREEN_PATH = {
  LOGIN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER_SCREEN',
  DASHBOARD: 'DASHBOARD_SCREEN',
  PRODUCT: 'PRODUCT_SCREEN',
  TRANSACTION: 'TRANSACTION_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  MAIN_APP: 'MAIN_APP',
};

const TAB_PATH = {
  DASHBOARD: 'Halaman Utama',
  PRODUCT: 'Produk',
  TRANSACTION: 'Transaksi',
  PROFILE: 'Profil'
};

export { SCREEN_PATH, TAB_PATH };